---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.22.3
    app.quarkus.io/commit-id: 3958b24e49c6f8df7c1d9b78900c35998764c5d5
    app.quarkus.io/vcs-uri: https://github.com/halkyonio/java-package-operator.git
    app.quarkus.io/build-timestamp: 2025-06-02 - 15:59:43 +0000
  labels:
    app.kubernetes.io/name: package-operator
    app.kubernetes.io/version: 0.1.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: package-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: package-operator
    app.kubernetes.io/version: 0.1.0-SNAPSHOT
  name: platformreconciler-cluster-role
rules:
  - apiGroups:
      - halkyon.io
    resources:
      - platforms
      - platforms/status
      - platforms/finalizers
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - create
      - delete
  - apiGroups:
      - halkyon.io
    resources:
      - packages
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: package-operator
    app.kubernetes.io/version: 0.1.0-SNAPSHOT
  name: josdk-crd-validating-cluster-role
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: package-operator
    app.kubernetes.io/version: 0.1.0-SNAPSHOT
  name: platformreconciler-crd-validating-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: josdk-crd-validating-cluster-role
subjects:
  - kind: ServiceAccount
    name: package-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: package-operator
    app.kubernetes.io/version: 0.1.0-SNAPSHOT
  name: platformreconciler-cluster-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: platformreconciler-cluster-role
subjects:
  - kind: ServiceAccount
    name: package-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: package-operator
    app.kubernetes.io/version: 0.1.0-SNAPSHOT
  name: package-operator-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: package-operator
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.22.3
    app.quarkus.io/commit-id: 3958b24e49c6f8df7c1d9b78900c35998764c5d5
    app.quarkus.io/vcs-uri: https://github.com/halkyonio/java-package-operator.git
    app.quarkus.io/build-timestamp: 2025-06-02 - 15:59:43 +0000
  labels:
    app.kubernetes.io/name: package-operator
    app.kubernetes.io/version: 0.1.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: package-operator
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: package-operator
    app.kubernetes.io/version: 0.1.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.22.3
    app.quarkus.io/commit-id: 3958b24e49c6f8df7c1d9b78900c35998764c5d5
    app.quarkus.io/vcs-uri: https://github.com/halkyonio/java-package-operator.git
    app.quarkus.io/build-timestamp: 2025-06-02 - 15:59:43 +0000
  labels:
    app.kubernetes.io/name: package-operator
    app.kubernetes.io/version: 0.1.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: package-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: package-operator
      app.kubernetes.io/version: 0.1.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.22.3
        app.quarkus.io/commit-id: 3958b24e49c6f8df7c1d9b78900c35998764c5d5
        app.quarkus.io/vcs-uri: https://github.com/halkyonio/java-package-operator.git
        app.quarkus.io/build-timestamp: 2025-06-02 - 15:59:43 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: package-operator
        app.kubernetes.io/version: 0.1.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/cmoullia/package-operator:0.1.0-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: package-operator
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccountName: package-operator
