apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: platform
  name: platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-sa-cluster-admin-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: platform
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-sa-cluster-admin-binding
subjects:
  - kind: ServiceAccount
    name: package-operator
    namespace: platform
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io