apiVersion: halkyon.io/v1alpha1
kind: Package
metadata:
  name: my-helm-app
  namespace: default
spec:
  tool: Helm
  url: https://charts.helm.sh/stable/nginx-ingress-1.41.3.tgz
  version: 1.41.3
  valuesObject:
    ingress:
      enabled: true
      path: /