apiVersion: halkyon.io/v1alpha1
kind: Platform
metadata:
  name: idpbuilder
  namespace: platform
spec:
  version: 0.1.0
  description: "The idpbuilder platform definition: ingress, gitea & argocd."
  packages:
    - name: nginx-ingress
      description: "nginx-ingress package"
      pipeline:
        steps:
          - name: install
            image: dtzar/helm-kubectl
            namespace:
              name: default
            helm:
              chart:
                repoUrl: https://kubernetes.github.io/ingress-nginx
                name: ingress-nginx
                version: 4.12.2
              values: |
                controller:
                  hostPort:
                    enabled: true
                  service:
                    type: NodePort
                ingress:
                  enabled: true

    - name: gitea
      description: "gitea package"
      pipeline:
        steps:
          - name: init
            image: dtzar/helm-kubectl
            namespace:
              name: default
            waitCondition:
              type: service
              endpoint:
                name: ingress-nginx-controller-admission
                port: 443
              path: /health

          - name: install
            image: dtzar/helm-kubectl
            namespace:
              name: gitea
            helm:
              chart:
                repoUrl: https://dl.gitea.com/charts/
                name: gitea
              values: |
                redis-cluster:
                  enabled: false
                postgresql:
                  enabled: false
                postgresql-ha:
                  enabled: false
                valkey-cluster:
                  enabled: false
                persistence:
                  enabled: false
                gitea:
                  admin:
                    # existingSecret: <NAME_OF_SECRET>
                    username: "giteaAdmin"
                    password: "developer"
                    email: "gi@tea.com"
                  config:
                    database:
                      DB_TYPE: sqlite3
                    session:
                      PROVIDER: memory
                    cache:
                      ADAPTER: memory
                    queue:
                      TYPE: level
                service:
                  ssh:
                    type: NodePort
                    nodePort: 32222
                    externalTrafficPolicy: Local
                ingress:
                  enabled: true
                  className: nginx
                  hosts:
                    - host: gitea.localtest.me
                      paths:
                        - path: /
                          pathType: Prefix
    - name: argocd
      description: "argocd package"
      pipeline:
        steps:
          - name: install
            image: dtzar/helm-kubectl
            namespace:
              name: argocd
            helm:
              chart:
                repoUrl: https://argoproj.github.io/argo-helm
                name: argo-cd
              release:
                name: argocd
              values: |
                configs:
                  secret:
                    argocdServerAdminPassword: $2a$10$lsTGT/O94tQBTs4gdtQmBuQ3R3jgfSizvPSzl6ySt2cn6OktKVwAy
                global:
                  domain: argocd.localtest.me
                certificate:
                  enabled: true
                server:
                  ingress:
                    enabled: true
                    ingressClassName: nginx
                    annotations:
                      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
                      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
                      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
                    tls: true