apiVersion: halkyon.io/v1alpha1
kind: Platform
metadata:
  name: generate-helm-command
  namespace: platform
spec:
  packages:
    - name: generate-helm-command
      pipeline:
        steps:
          - name: install
            image: dtzar/helm-kubectl
            namespace:
              name: default
              createNamespace: true
            helm:
              chart:
                repoUrl: https://kubernetes.github.io/ingress-nginx
                name: ingress-nginx
                version: 4.12.2
              values: |
                controller:
                  hostPort:
                    enabled: true
                  service:
                    type: NodePort
                ingress:
                  enabled: true
