apiVersion: halkyon.io/v1alpha1
kind: Platform
metadata:
  name: ingress-gitea
  namespace: platform
spec:
  version: 0.1.0
  description: "A platform example installing the following packages nginx ingress and gitea and exposing the gitea ui at the address https://gitea.localtest.me:8443"
  packages:
    - name: nginx-ingress
      description: "nginx-ingress package"
      pipeline:
        steps:
          - name: install
            image: dtzar/helm-kubectl
            helm:
              chart:
                repoUrl: https://kubernetes.github.io/ingress-nginx
                name: ingress-nginx
                version: 4.12.2
              values: |
                controller:
                  hostPort:
                    enabled: true
                  service:
                    type: NodePort
                ingress:
                  enabled: true

    - name: gitea
      description: "gitea package"
      pipeline:
        steps:
          - name: init
            image: dtzar/helm-kubectl
            namespace:
              name: default
            waitCondition:
              type: service
              endpoint:
                name: ingress-nginx-controller-admission
                port: 443
              path: /health
            #script: |
            #  echo "WaitFor Ingress"
            #  until curl -s http://ingress-nginx-controller-admission.default:443/healthz; do
            #    echo "Waiting for service to be ready..."
            #    sleep 5
            #  done

          - name: install
            image: dtzar/helm-kubectl
            namespace:
              name: gitea
            helm:
              chart:
                repoUrl: https://dl.gitea.com/charts/
                name: gitea
              values: |
                redis-cluster:
                  enabled: false
                postgresql:
                  enabled: false
                postgresql-ha:
                  enabled: false
                valkey-cluster:
                  enabled: false
                persistence:
                  enabled: false
                gitea:
                  admin:
                    # existingSecret: <NAME_OF_SECRET>
                    username: "giteaAdmin"
                    password: "developer"
                    email: "gi@tea.com"
                  config:
                    database:
                      DB_TYPE: sqlite3
                    session:
                      PROVIDER: memory
                    cache:
                      ADAPTER: memory
                    queue:
                      TYPE: level
                service:
                  ssh:
                    type: NodePort
                    nodePort: 32222
                    externalTrafficPolicy: Local
                ingress:
                  enabled: true
                  className: nginx
                  hosts:
                    - host: gitea.localtest.me
                      paths:
                        - path: /
                          pathType: Prefix