apiVersion: halkyon.io/v1alpha1
kind: Platform
metadata:
  name: simple-platform
spec:
  version: 0.1.0
  description: "A simple platform"
  packages:
    - name: nginx-ingress
      description: "nginx-ingress package"
      #pipeline:
      #  steps:
      #  - name: pre-install
      #    image: registry.access.redhat.com/ubi9
      #    script: |
      #      echo "This is a pre-installation running a job"
      #  - name: install-nginx-ingress
      #    image: dtzar/helm-kubectl
      #    repoUrl: https://kubernetes.github.io/ingress-nginx
      #    version: 4.12.2
      #    script: |
      #      cat << EOF > values.yml
      #      ingress:
      #        enabled: true
      #      EOF
      #      helm repo add kubernetes.github.io/ingress-nginx
      #      helm repo update
      #      helm install nginx-ingress ingress-nginx/ingress-nginx \
      #         --version 4.12.2 \
      #         --namespace ingress-nginx \
      #         --create-namespace \
      #         -f values.yml
      #    values: |
      #      ingress:
      #        enabled: true
      #  - name: post-install
      #    image: registry.access.redhat.com/ubi9
      #    script: |
      #      echo "This is a post-installation running a job"
    - name: gitea
      description: "gitea package"
    - name: argocd
      description: "argocd package"