name: Deploy the maven artifacts signed on Maven Central
on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
          server-id: central
          server-username: MAVEN_USERNAME # ${{ secrets.MAVEN_USERNAME }}
          server-password: MAVEN_PASSWORD # ${{ secrets.MAVEN_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # Don't work => ${{ secrets.GPG_PASSPHRASE }} as env var name should be defined

      - name: Check the gpg key
        run: |
          gpg --list-keys

      - name: Publish package
        run: |
          mvn -B -ntp deploy -DskipTests -Prelease
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Create release
        uses: release-drafter/release-drafter@v6
            # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
            # with:
            #   config-name: my-config.yml
            #   disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #- name: Create release
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    tag: ${{ github.ref_name }}
      #  run: |
      #    gh release create "$tag" \
      #        --repo="$GITHUB_REPOSITORY" \
      #        --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
      #        --generate-notes